### PR TITLE
bug fix for when user clicks Cancel at acceptance screen

### PR DESCRIPTION
**Pull request by joshkendrick**
This library is really great! It's helped me integrate google login in no time!

The only issue I found was (at least in Chrome), if a user went to the 'cancel'/'accept' screen and hit cancel, they would be infinitely redirected back to .../oauth2callback? over and over. I tried many different ways of changing my route and I didn't make any progress. The code looked simple enough, so I just put in a fix that sends data back to the view method, and from there the developer could decide what to do? Below I just redirect the user back to the login view.

Please reject the pull request if you had a better/smarter way to fix this!

Again thanks for all the work so far.

Oh and since I've made use of it recently, I could take some time to flesh out some documentation or add some comments to the example. I had a few other issues I ran into that it might be useful to note in the code..

### CODE REVIEW

**Comment by marksteve** [comment]
Thanks for reporting this. It's embarrassing to say that I didn't think about this case. Will check your changes tomorrow morning (it's sun 11pm here atm).

**Comment by joshkendrick** [comment]
bah i've done it before too. it's good to just get another set of hands on your code and have someone look at it with a fresh pair of eyes.

**Comment by bugsduggan** [comment]
Any progress with this? Looks like it's ready to merge.

**Comment by macrojames** [comment]
I would love to see this merged! It was quite annoying until I found this issue.

**Comment by kvas-it** [comment]
I just produced a similar fix and it turns out I don't need to send a pull request :) Please accept my vote for merging this one though.

**Pull request closed without merging**
